[package]
name = "dotfile-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8.13"
clap = { version = "4.5.4", features = ["derive"] }
# serde = { version = "1.0.203", features = ["derive"] }
